module.exports = {
  data: [
    {
      question: "Who was King Ahab's wife?",
      option1: "Ruth",
      option2: "Mary",
      option3: "Jezebel",
      option4: "Rebecca",
      ans: 3,
    },
    {
      question: "Who led the Israelites into the Promised Land?",
      option1: "Moses",
      option2: "Joshua",
      option3: "Abraham",
      option4: "Isaac",
      ans: 2,
    },
    {
      question: "Who was thrown into a lion's den?",
      option1: "David",
      option2: "Solomon",
      option3: "Daniel",
      option4: "Joseph",
      ans: 3,
    },
    {
      question: "Who killed Goliath?",
      option1: "Saul",
      option2: "David",
      option3: "Samson",
      option4: "Jonathan",
      ans: 2,
    },
    {
      question: "Who was sold into slavery by his brothers?",
      option1: "Moses",
      option2: "Aaron",
      option3: "Joseph",
      option4: "Simon",
      ans: 3,
    },
    {
      question: "Who was the first king of Israel?",
      option1: "Saul",
      option2: "David",
      option3: "Solomon",
      option4: "Samuel",
      ans: 1,
    },
    {
      question: "Who interpreted dreams in Egypt?",
      option1: "Joseph",
      option2: "Daniel",
      option3: "Moses",
      option4: "Pharaoh",
      ans: 1,
    },
    {
      question: "Who built the ark?",
      option1: "Noah",
      option2: "Moses",
      option3: "Abraham",
      option4: "Jacob",
      ans: 1,
    },
    {
      question: "Who was swallowed by a great fish?",
      option1: "Jonah",
      option2: "Peter",
      option3: "James",
      option4: "John",
      ans: 1,
    },
    {
      question: "Who was the strongest man in the Bible?",
      option1: "Goliath",
      option2: "Samson",
      option3: "David",
      option4: "Saul",
      ans: 2,
    },
    {
      question: "Who baptized Jesus?",
      option1: "Peter",
      option2: "Paul",
      option3: "John the Baptist",
      option4: "James",
      ans: 3,
    },
    {
      question: "Who was the first disciple to be martyred?",
      option1: "Stephen",
      option2: "James",
      option3: "Peter",
      option4: "John",
      ans: 2,
    },
    {
      question: "Who wrote the book of Revelation?",
      option1: "Paul",
      option2: "Peter",
      option3: "John",
      option4: "James",
      ans: 3,
    },
    {
      question: "Who was the first man created?",
      option1: "Adam",
      option2: "Eve",
      option3: "Cain",
      option4: "Abel",
      ans: 1,
    },
    {
      question: "Who was known for his wisdom?",
      option1: "David",
      option2: "Solomon",
      option3: "Samuel",
      option4: "Saul",
      ans: 2,
    },
    {
      question: "Who built the temple in Jerusalem?",
      option1: "David",
      option2: "Solomon",
      option3: "Rehoboam",
      option4: "Hezekiah",
      ans: 2,
    },
    {
      question:
        "Who was the prophet that confronted King David about his sin with Bathsheba?",
      option1: "Nathan",
      option2: "Elijah",
      option3: "Elisha",
      option4: "Samuel",
      ans: 1,
    },
    {
      question: "Who was the oldest man in the Bible?",
      option1: "Noah",
      option2: "Methuselah",
      option3: "Adam",
      option4: "Seth",
      ans: 2,
    },
    {
      question: "Who was turned into a pillar of salt?",
      option1: "Lot's wife",
      option2: "Sarah",
      option3: "Rebekah",
      option4: "Rachel",
      ans: 1,
    },
    {
      question: "Who was the father of many nations?",
      option1: "Isaac",
      option2: "Jacob",
      option3: "Abraham",
      option4: "Joseph",
      ans: 3,
    },
    {
      question: "Who wrestled with an angel?",
      option1: "Jacob",
      option2: "Esau",
      option3: "Isaac",
      option4: "Abraham",
      ans: 1,
    },
    {
      question: "Who was the first martyr in the New Testament?",
      option1: "Stephen",
      option2: "James",
      option3: "Peter",
      option4: "John",
      ans: 1,
    },
    {
      question: "Who was caught up to the third heaven?",
      option1: "John",
      option2: "Paul",
      option3: "Peter",
      option4: "James",
      ans: 2,
    },
    {
      question: "Who replaced Judas as the twelfth apostle?",
      option1: "Matthias",
      option2: "Barnabas",
      option3: "Timothy",
      option4: "Silas",
      ans: 1,
    },
    {
      question: "Who was known as the weeping prophet?",
      option1: "Isaiah",
      option2: "Jeremiah",
      option3: "Ezekiel",
      option4: "Daniel",
      ans: 2,
    },
    {
      question: "Who interpreted Nebuchadnezzar's dream?",
      option1: "Daniel",
      option2: "Joseph",
      option3: "Ezekiel",
      option4: "Jeremiah",
      ans: 1,
    },
    {
      question: "Who was the queen of Persia who saved her people?",
      option1: "Vashti",
      option2: "Esther",
      option3: "Ruth",
      option4: "Deborah",
      ans: 2,
    },
    {
      question: "Who was the father of John the Baptist?",
      option1: "Zacharias",
      option2: "Elizabeth",
      option3: "Aaron",
      option4: "Simon",
      ans: 1,
    },
    {
      question: "Who walked on water with Jesus?",
      option1: "John",
      option2: "Peter",
      option3: "James",
      option4: "Andrew",
      ans: 2,
    },
    {
      question: "Who was the tax collector called by Jesus?",
      option1: "Zacchaeus",
      option2: "Matthew",
      option3: "Simon",
      option4: "Judas",
      ans: 2,
    },
    {
      question: "Who was the disciple known as the doubter?",
      option1: "Thomas",
      option2: "James",
      option3: "Peter",
      option4: "John",
      ans: 1,
    },
    {
      question: "Who was the first person to see the risen Christ?",
      option1: "Mary Magdalene",
      option2: "Peter",
      option3: "John",
      option4: "Thomas",
      ans: 1,
    },
    {
      question: "Who was the king of Judea at the time of Jesus' birth?",
      option1: "Herod the Great",
      option2: "Pontius Pilate",
      option3: "Augustus",
      option4: "Tiberius",
      ans: 1,
    },
    {
      question: "Who was Paul's companion on his first missionary journey?",
      option1: "Silas",
      option2: "Barnabas",
      option3: "Timothy",
      option4: "Luke",
      ans: 2,
    },
    {
      question:
        "Who was the prophetess who recognized Jesus as the Messiah when he was presented at the Temple?",
      option1: "Anna",
      option2: "Deborah",
      option3: "Huldah",
      option4: "Miriam",
      ans: 1,
    },
    {
      question: "Who was the Roman governor who sentenced Jesus to death?",
      option1: "Herod Antipas",
      option2: "Tiberius",
      option3: "Pontius Pilate",
      option4: "Nero",
      ans: 3,
    },
    {
      question: "Who was the angel that announced the birth of Jesus to Mary?",
      option1: "Michael",
      option2: "Gabriel",
      option3: "Raphael",
      option4: "Uriel",
      ans: 2,
    },
    {
      question:
        "Who was the king who had a dream of a statue made of different metals?",
      option1: "Belshazzar",
      option2: "Darius",
      option3: "Cyrus",
      option4: "Nebuchadnezzar",
      ans: 4,
    },
    {
      question: "Who was the disciple that Jesus loved?",
      option1: "Peter",
      option2: "John",
      option3: "James",
      option4: "Andrew",
      ans: 2,
    },
    {
      question: "Who was the prophet that was fed by ravens?",
      option1: "Elijah",
      option2: "Elisha",
      option3: "Isaiah",
      option4: "Jeremiah",
      ans: 1,
    },
    {
      question:
        "Who was the brother of Mary and Martha, whom Jesus raised from the dead?",
      option1: "Lazarus",
      option2: "Jairus",
      option3: "Bartimaeus",
      option4: "Nicodemus",
      ans: 1,
    },
    {
      question: "Who was the woman at the well Jesus spoke to?",
      option1: "Samaritan woman",
      option2: "Syrophoenician woman",
      option3: "Canaanite woman",
      option4: "Phoenician woman",
      ans: 1,
    },
    {
      question: "Who was the high priest who put Jesus on trial?",
      option1: "Annas",
      option2: "Caiaphas",
      option3: "Aaron",
      option4: "Eli",
      ans: 2,
    },
    {
      question:
        "Who was the Roman centurion who declared, 'Truly this was the Son of God!' at Jesus' crucifixion?",
      option1: "Cornelius",
      option2: "Julius",
      option3: "Claudius",
      option4: "Unnamed centurion",
      ans: 4,
    },
    {
      question: "Who was the disciple who replaced Judas Iscariot?",
      option1: "Matthias",
      option2: "Bartholomew",
      option3: "Thaddaeus",
      option4: "Philip",
      ans: 1,
    },
    {
      question: "Who was the father of Isaac?",
      option1: "Abraham",
      option2: "Lot",
      option3: "Nahor",
      option4: "Terah",
      ans: 1,
    },
    {
      question: "Who was the king of Babylon who saw the writing on the wall?",
      option1: "Nebuchadnezzar",
      option2: "Belshazzar",
      option3: "Darius",
      option4: "Cyrus",
      ans: 2,
    },
    {
      question: "Who was the woman who hid the spies in Jericho?",
      option1: "Rahab",
      option2: "Deborah",
      option3: "Jael",
      option4: "Esther",
      ans: 1,
    },
    {
      question: "Who was the apostle known as 'the zealot'?",
      option1: "Simon",
      option2: "Jude",
      option3: "Matthew",
      option4: "Thaddaeus",
      ans: 1,
    },
    {
      question: "Who was the prophet who anointed Saul as king?",
      option1: "Samuel",
      option2: "Nathan",
      option3: "Elijah",
      option4: "Elisha",
      ans: 1,
    },
  ],
};
